export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const INCREMENT_COMMENT = 'INCREMENT_COMMENT';
export const DECREMENT_COMMENT = 'DECREMENT_COMMENT';